### ISSUE TITLE
Exporter crashes/false readings when called simultaneously 

### ISSUE THREAD

**Issue by aneliya-n-ivanova** [casa-delle-coccinelle/rpi-sensors-exporter#1]
When GET /metrics is performed simultaneously it causes crashes and/or false readings from the sensors.

Most probably due to already ongoing measurement from the sensors. Especially notable with BME688 because of the gas resistance reading hardware.

**Comment by mimiteto** [comment]
Fixed in https://github.com/casa-delle-coccinelle/rpi-sensors-exporter/pull/6
